from __future__ import annotations

import re
from pathlib import Path
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, ValidationError, model_validator

from .journal_client import (
    JournalLLMResponseError,
    JournalModelLockError,
    StrictJournalOllamaClient,
)
from .schemas import (
    HCAIRequirements,
    ObjectiveLabel,
    ObjectiveSelectionResult,
)


CANONICAL_OBJECTIVES = ("Accuracy", "Runtime", "Energy", "CO2")


class _JournalSelectionPayload(BaseModel):
    """Literal output schema generated by the frozen Phase-10 prompt."""

    model_config = ConfigDict(extra="forbid")

    status: str
    selected_objectives: List[ObjectiveLabel] = Field(default_factory=list)
    uncertainties: List[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_payload(self):
        allowed_status = {"valid", "ambiguous", "contradictory", "out_of_scope"}
        if self.status not in allowed_status:
            raise ValueError("Unsupported journal selection status.")
        if len(set(self.selected_objectives)) != len(self.selected_objectives):
            raise ValueError("Duplicate objective labels are not allowed.")
        if self.status == "valid" and not self.selected_objectives:
            raise ValueError("A valid response must select at least one objective.")
        return self


class GoalSelectionError(ValueError):
    pass


def _contains_any(text: str, phrases) -> bool:
    return any(phrase in text for phrase in phrases)


def deterministic_objective_selection(text: str) -> ObjectiveSelectionResult:
    """Transparent interactive fallback, not the Phase-12 evaluation model."""

    t = re.sub(r"\s+", " ", (text or "").lower()).strip()
    if not t:
        return ObjectiveSelectionResult(
            status="ambiguous",
            selected_objectives=[],
            uncertainties=["No scenario was provided."],
            source="deterministic",
        )

    contradictory_patterns = [
        ("ignore accuracy", "accuracy"),
        ("do not care about speed", "as fast as possible"),
        ("ignore energy", "battery"),
        ("ignore carbon", "lowest emissions"),
    ]
    for left, right in contradictory_patterns:
        if left in t and right in t:
            return ObjectiveSelectionResult(
                status="contradictory",
                selected_objectives=[],
                uncertainties=[
                    "The scenario contains conflicting objective cues: '{}' and '{}'.".format(
                        left, right
                    )
                ],
                source="deterministic",
            )

    selected = []

    accuracy_cues = [
        "accur",
        "correct",
        "predictive performance",
        "strong performance",
        "high performance",
        "dependable prediction",
        "reliable prediction",
        "prediction quality",
        "quality of prediction",
    ]
    runtime_cues = [
        "fast",
        "quick",
        "low latency",
        "real-time",
        "realtime",
        "time critical",
        "time-critical",
        "respond immediately",
        "speed",
        "runtime",
    ]
    energy_cues = [
        "energy",
        "power",
        "battery",
        "low-power",
        "low power",
        "edge device",
        "edge environment",
        "resource constrained device",
        "resource-constrained device",
    ]
    co2_cues = [
        "co2",
        "carbon",
        "emission",
        "climate",
        "green deployment",
        "environmental footprint",
        "low-impact",
        "low impact",
        "sustainable",
        "sustainability",
    ]

    if _contains_any(t, accuracy_cues):
        selected.append("Accuracy")
    if _contains_any(t, runtime_cues):
        selected.append("Runtime")
    if _contains_any(t, energy_cues):
        selected.append("Energy")
    if _contains_any(t, co2_cues):
        selected.append("CO2")

    if selected:
        return ObjectiveSelectionResult(
            status="valid",
            selected_objectives=selected,
            uncertainties=[],
            source="deterministic",
        )

    generic = ["good", "best", "balanced", "better", "optimal", "user happiness"]
    if _contains_any(t, generic):
        return ObjectiveSelectionResult(
            status="ambiguous",
            selected_objectives=[],
            uncertainties=[
                "The scenario does not imply a unique subset of Accuracy, Runtime, Energy, and CO2."
            ],
            source="deterministic",
        )

    return ObjectiveSelectionResult(
        status="out_of_scope",
        selected_objectives=[],
        uncertainties=[
            "No supported primary objective could be inferred from the scenario."
        ],
        source="deterministic",
    )


def infer_hcai_requirements(text: str) -> HCAIRequirements:
    """HCAI requirements are deliberately separate from primary objectives."""

    t = (text or "").lower()

    drift_sensitivity = (
        "high"
        if _contains_any(
            t,
            [
                "concept drift",
                "drift",
                "non-stationary",
                "nonstationary",
                "adapt quickly",
                "recover quickly",
            ],
        )
        else "moderate"
    )

    fairness_required = _contains_any(
        t,
        ["fair", "fairness", "bias", "equity", "protected group"],
    )

    fairness_metric = None
    if "equal opportunity" in t:
        fairness_metric = "equal_opportunity"
    elif "equalized odds" in t:
        fairness_metric = "equalized_odds"
    elif "demographic parity" in t:
        fairness_metric = "demographic_parity"

    explainability_level = (
        "high"
        if _contains_any(
            t,
            [
                "explain",
                "interpretable",
                "interpretability",
                "transparent",
                "understandable",
            ],
        )
        else "moderate"
    )

    energy_constraint = "low"
    if _contains_any(
        t,
        ["strict energy", "very low energy", "minimize energy", "lowest energy"],
    ):
        energy_constraint = "strict"
    elif _contains_any(t, ["energy", "power", "battery", "edge device", "edge environment"]):
        energy_constraint = "moderate"

    runtime_match = re.search(
        r"(?:under|within|max(?:imum)?|no more than)[^0-9]{0,18}"
        r"(\d+(?:\.\d+)?)\s*(?:s|sec|secs|second|seconds)\b",
        t,
    )
    max_runtime_sec = float(runtime_match.group(1)) if runtime_match else None

    return HCAIRequirements(
        drift_sensitivity=drift_sensitivity,
        energy_constraint=energy_constraint,
        fairness_required=fairness_required,
        fairness_metric=fairness_metric,
        explainability_level=explainability_level,
        max_runtime_sec=max_runtime_sec,
    )


class JournalObjectiveSelector:
    """Problem A: frozen scenario -> objective-set inference."""

    def __init__(
        self,
        client: Optional[StrictJournalOllamaClient] = None,
        root: Optional[Path] = None,
    ):
        self.client = client or StrictJournalOllamaClient(root=root)
        protocol = self.client.protocol
        self.root = self.client.root
        self.prompt_path = self.root / protocol["journal_llm"]["prompt_file"]
        self.template = self.prompt_path.read_text(encoding="utf-8")

    def render_prompt(self, scenario: str) -> str:
        if "{{USER_SCENARIO}}" not in self.template:
            raise JournalModelLockError(
                "Frozen journal prompt is missing {{USER_SCENARIO}} placeholder."
            )
        return self.template.replace("{{USER_SCENARIO}}", str(scenario).strip())

    def select(self, scenario: str) -> ObjectiveSelectionResult:
        prompt = self.render_prompt(scenario)

        try:
            payload, meta = self.client.generate_json(prompt)
        except JournalModelLockError:
            # Model/runtime mismatch is a benchmark-invalidating error, not a
            # parse failure and never receives a deterministic fallback.
            raise
        except JournalLLMResponseError as exc:
            return ObjectiveSelectionResult(
                status="malformed",
                selected_objectives=[],
                uncertainties=[str(exc)],
                source="journal-ollama",
                model=getattr(self.client, "model", None),
                fallback_used=False,
            )

        try:
            parsed = _JournalSelectionPayload.model_validate(payload)
        except (ValidationError, ValueError) as exc:
            return ObjectiveSelectionResult(
                status="malformed",
                selected_objectives=[],
                uncertainties=[
                    "Journal objective JSON rejected: {}: {}".format(
                        type(exc).__name__, exc
                    )
                ],
                source="journal-ollama",
                model=meta.get("model"),
                fallback_used=False,
            )

        return ObjectiveSelectionResult(
            status=parsed.status,
            selected_objectives=parsed.selected_objectives,
            uncertainties=parsed.uncertainties,
            source=meta.get("source", "journal-ollama"),
            model=meta.get("model"),
            fallback_used=False,
        )
