from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from phase18_common import (  # noqa: E402
    DATASET_DIR,
    EXPECTED_AGGREGATED,
    EXPECTED_DATASETS,
    EXPECTED_PREFERENCE_CASES,
    EXPECTED_RUNS,
    FREEZE_CONFIRMATION,
    PREFLIGHT_DIR,
    PROTOCOL_ID,
    audit_datasets,
    audit_summary,
    freeze_protocol,
    resolution_template,
    sha256_file,
    write_json_atomic,
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Comprehensive Phase-18 audit and strict freeze gate. "
            "This script reports every dataset issue in one pass and never silently "
            "waives development overlap or converts regression-like targets."
        )
    )
    parser.add_argument(
        "--dataset-dir",
        type=Path,
        default=DATASET_DIR,
        help="Directory containing the local testing CSVs; 31 are declared by this protocol.",
    )
    parser.add_argument("--audit", action="store_true", help="Run the comprehensive audit only.")
    parser.add_argument(
        "--freeze",
        action="store_true",
        help="Freeze the explicit 31-dataset task policy after all rows pass separation and task-construction checks.",
    )
    parser.add_argument(
        "--confirm",
        default="",
        help=f"Required with --freeze after reviewing the audit: {FREEZE_CONFIRMATION}",
    )
    args = parser.parse_args()

    if args.audit and args.freeze:
        raise SystemExit("Choose either --audit or --freeze, not both.")

    dataset_dir = args.dataset_dir.expanduser().resolve()
    if args.freeze and dataset_dir != DATASET_DIR.resolve():
        raise SystemExit(
            "Final freeze requires the canonical dataset directory: {}".format(DATASET_DIR)
        )

    print("=" * 78)
    print("AwareML Phase 18 — 31-dataset task-policy preparation v2.5")
    print("=" * 78)
    print("Protocol:", PROTOCOL_ID)
    print("Dataset directory:", dataset_dir)
    print("Source datasets declared:", EXPECTED_DATASETS)
    print("Framework runs:", EXPECTED_RUNS)
    print("Aggregated rows:", EXPECTED_AGGREGATED)
    print("Preference cases:", EXPECTED_PREFERENCE_CASES)
    print("Framework execution: DISABLED in this preparation script")
    print()

    audit = audit_datasets(dataset_dir)
    PREFLIGHT_DIR.mkdir(parents=True, exist_ok=True)
    audit_path = PREFLIGHT_DIR / "dataset_audit.tsv"
    audit.to_csv(audit_path, sep="\t", index=False)

    summary = audit_summary(audit)
    summary_path = PREFLIGHT_DIR / "dataset_audit_summary.json"
    write_json_atomic(summary_path, summary)

    resolution = resolution_template(audit)
    resolution_path = PREFLIGHT_DIR / "dataset_resolution_template.tsv"
    resolution.to_csv(resolution_path, sep="\t", index=False)

    display_cols = [
        "dataset_id",
        "cohort",
        "rows_in_file",
        "resolved_target",
        "target_unique",
        "task_assessment",
        "preflight_status",
        "evaluation_role",
        "primary_heldout_eligible",
    ]
    available = [c for c in display_cols if c in audit.columns]
    print(audit[available].to_string(index=False))
    print()
    print("Audit summary:", json.dumps(summary, indent=2, ensure_ascii=False))
    print()
    print("Wrote:", audit_path)
    print("SHA256:", sha256_file(audit_path))
    print("Wrote:", summary_path)
    print("Wrote:", resolution_path)

    if not args.freeze:
        eligible = int(audit["primary_heldout_eligible"].astype(bool).sum())
        print()
        print(f"Protocol-ready datasets: {eligible}/{EXPECTED_DATASETS}")
        print("If all 31 are protocol-ready, run --freeze with the exact confirmation token shown in the README.")
        return

    print()
    print("Attempting immutable 31-dataset pre-outcome freeze...")
    try:
        lock = freeze_protocol(audit, args.confirm)
    except RuntimeError as exc:
        print()
        print("FREEZE BLOCKED")
        print(str(exc))
        raise SystemExit(2)

    print("Freeze created successfully.")
    print(json.dumps(lock["expected_counts"], indent=2))
    print(
        "Protocol lock:",
        ROOT / "data" / "journal" / "phase18_final_heldout_31_v1" / "frozen" / "protocol_lock.json",
    )
    print()
    print("No held-out framework outcome was generated by this command.")


if __name__ == "__main__":
    main()
